variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable avail_zone {}
variable env_prefix {}
variable my_ip {}
variable eip_id {}
variable instance_type {}
variable public_key_location {}
variable private_key_location {}
variable image_name {}
variable domain_name {}
variable dns_address {}
variable rds_address {}